/**
 * Sky and clouds behind the hero.
 *
 * Two layers, in this order:
 *
 *   1. A CSS gradient sky. This is the floor, not a placeholder. If the image
 *      404s, is still in flight, or the connection dies, the hero still has a
 *      sky and navy type still reads against it.
 *   2. A generated sky photograph on top, art-directed per breakpoint.
 *
 * The image is generated by `scripts/make-sky.py` rather than prompted. Three
 * generated skies were tried first and all three came back as a flat pale wash with
 * a few wisps in the corners -- at hero scale, under the horizon fade, no cloud was
 * visible at all. The procedural version places the composition instead of hoping
 * for it, and re-renders in seconds when it needs tuning.
 *
 * Cost is still measured, not assumed: 23 KB desktop, 20 KB mobile as WebP, because
 * soft cloud is close to the best case for that codec.
 *
 * Contrast is asserted by the generator, not eyeballed here. Across the centre band
 * where the headline, price deck and CTA actually sit, the darkest cell gives 8.8:1
 * against navy ink on desktop and 10.2:1 on the portrait crop. AA wants 4.5:1, and
 * the script exits non-zero if a crop ever falls under it.
 *
 * The metaphor is why this is here at all: masa depan cerah. A clear sky is the
 * plainest picture of a bright future, and it is also why the palette dropped gold
 * for blue.
 *
 * Server component: no state, no effects, no JS shipped.
 */
export function SkyBackdrop({ className = "" }: { className?: string }) {
  return (
    <div
      aria-hidden="true"
      className={`pointer-events-none absolute inset-0 overflow-hidden ${className}`}
    >
      {/* Layer 1: CSS sky. Always present, never waits on the network. Sampled from the
          generated image so a slow or failed load shifts nothing but the clouds. */}
      <div className="absolute inset-0 bg-[linear-gradient(to_bottom,#80b6e4_0%,#a9cfef_28%,#dcecf9_62%,#f9fcff_100%)]" />

      {/* Layer 2: the photograph, art-directed. Portrait crop below sm so the
          clouds stay in the upper third on a phone instead of being cropped to
          a flat wash. */}
      <picture>
        <source
          media="(max-width: 639px)"
          srcSet="/sky/hero-sky-mobile.webp"
          type="image/webp"
        />
        <img
          src="/sky/hero-sky.webp"
          alt=""
          decoding="async"
          fetchPriority="high"
          className="absolute inset-0 size-full object-cover"
        />
      </picture>

      {/* Drifting cloud veils over the image. Kept at low opacity on purpose: the
          image now carries real cloud structure, and anything heavier here reads as a
          second, contradictory weather system sliding over the first. */}
      <div
        className="sky-drift absolute inset-x-0 top-[12%] h-[46%] opacity-25"
        style={{
          backgroundImage: [
            "radial-gradient(34% 44% at 14% 60%, rgba(255,255,255,0.85) 0%, rgba(255,255,255,0) 72%)",
            "radial-gradient(40% 48% at 80% 56%, rgba(255,255,255,0.80) 0%, rgba(255,255,255,0) 72%)",
          ].join(","),
        }}
      />

      {/* Horizon wash so type near the bottom always has a calm ground under it, and so
          the section melts into the white band that follows. Held to the bottom quarter
          and ramped late: at a third of the height it erased the low cloud bank the
          generator places along the foot of the frame. */}
      <div className="absolute inset-x-0 bottom-0 h-1/4 bg-[linear-gradient(to_bottom,rgba(255,255,255,0)_0%,rgba(255,255,255,0.55)_58%,rgba(255,255,255,0.94)_86%,#ffffff_100%)]" />
    </div>
  );
}

export default SkyBackdrop;
